config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'home/contact'
  get 'home/news'
  root 'home#index'
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def contact
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	 def index
  	@projects=Project.all
  end

  def show
  	@project = Project.find(params[:id])
    @images= Project.find(params[:id]).images
  end

  def new
    @project = Project.new
  end
 
  def edit
    @project = Project.find(params[:id])
  end
 
  def create
    @project = Project.new(project_params)
 
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end
   def update
    @project = Project.find(params[:id])
 
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end
    def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end
  private
    def project_params
      params.require(:project).permit(:title, :text)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/about.html.erb
<div class="about-title">
		<p>关于 About</p>
</div>
<div class="container-about">

	<div class="about">
	
		<div class="about-title2">
			<p>亘心设计</p>
		</div>
		<div class="about-brief">
			<p>附属于集团房地产公司，既有传统的住宅、酒店项目建筑设计，利用3D打印建模；也有自己投资并参与和国外设计师合作的装置艺术设计等。我们给予建筑设计师完全的主动权，你有想法我们就能给予支持。我们就是一家行走在建筑与艺术之间的设计公司！</p>
		</div>
	</div>

</div>

app/views/home/contact.html.erb
	<div class="contact-title">
		<p>联系 Contact</p>
	</div>
<div class="container-contact">

	<div class="contact">
		<div class="contact-title2">
			<p>地址</p>
		</div>
		<div class="contact-brief">
			<p>延安西路1600号301室,上海</p>
		</div>
	</div>
		<div class="contact">
		<div class="contact-title2">
			<p>邮箱</p>
		</div>
		<div class="contact-brief">
			<p>email: office@genxindesign.com</p>
		</div>
	</div>
			<div class="contact">
		<div class="contact-title2">
			<p>电话</p>
		</div>
		<div class="contact-brief">
			<p>021-62267091</p>
		</div>
	</div>
	
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>

<body>
<div class="row">
  <div class="col-lg-10 offset-lg-1 col-md-12">
 <div id="carouselControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "homeimg1.jpg", :class => "d-block w-100 home-img" , :alt => "First slide"%> 
    </div>
    <div class="carousel-item ">
      <%= image_tag "homeimg2.jpg", :class => "d-block w-100 home-img" , :alt => "Second slide"%> 
    </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
</div>

</body>

</html>

app/views/home/news.html.erb
<div class="news-title">
		<p>新闻 News</p>
	</div>
<div class="container-news">
	
	<div class="news bg-light">
		<div class="news-title2">
			<p> 3d打印演讲</p>
		</div>
		<div class="news-brief ">
			<p>演讲介绍关于3d打印的知识</p>
		</div>
	</div>
	<div class="news  bg-light">
		<div class="news-title2">
			<p> 玩具改造采访</p>
		</div>
		<div class="news-brief">
			<p>采访小朋友，和小朋友一起玩玩具做视频</p>
		</div>
	</div>
		<div class="news  bg-light">
		<div class="news-title2">
			<p> 锄禾日当午</p>
		</div>
		<div class="news-brief">
			<p>汗滴禾下土</p>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Genxinstudio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <br> <br> <br> <br> <br>
                    <h1>Edit Post</h1>

                    <% if flash[:error] %>
                      <p><%= flash[:error] %></p>
                    <% end %>

                    <%= form_for @project do |f| %>
                    <fieldset>
                    <div>
                        <%= f.label :title %>
                        <%= f.text_field :title %>
                    </div>
                    <div>
                        <%= f.label :brief %>
                        <%= f.text_area :brief%>
                    </div>

                    <div>
                        <%= f.label :image1 %>
                        <%= f.text_area :image1%>
                    </div>
                    </fieldset>
                    <div> <%=f.submit "Add", :class => 'btn btn-default btn-lg'%>
                    <%end%>

                    <p class="btn btn-default btn-lg"><%= link_to "Cancel", project_path(@project) %></p>
                    </div>
                </div>
            </div>
        </div>

app/views/projects/index.html.erb
    <div class="col-lg-10 col-lg-offset-1 project_container">
      <div class="row">
        <% @projects.each do |project| %>
        <div class="col-md-3 col-sm-4">
          <div class="card card-project">
             <%= link_to project_path(project) do %>
            <div class="flip-box">
              <div class="flip-box-inner">
                <div class="flip-box-front">
                  <%= image_tag project.image1, :class => "card-img-top"%>
                 </div>
              </div>
              </div>

            <div class="card-body">
              <h1 class="card-title"> <%=project.title%></h1>
            </div>
          </div>
          <% end %>
        </div>
        <% end %> 
      </div> 
    </div>

    

app/views/projects/new.html.erb
<div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <br> <br> <br> <br> <br>
                    <h1>New project</h1>

                    <% if flash[:error] %>
                      <p><%= flash[:error] %></p>
                    <% end %>

                    <%= form_for @project do |f| %>
                    <fieldset>
                    <div>
                        <%= f.label :title %>
                        <%= f.text_field :title %>
                    </div>
                    <div>
                        <%= f.label :brief %>
                        <%= f.text_field :brief%>
                    </div>
                    <div>
                        <%= f.label :description %>
                        <%= f.text_field :description%>
                    </div>

                    <div>
                        <%= f.label :image1 %>
                        <%= f.text_area :image1%>
                    </div>
                    </fieldset>
                    <div> <%=f.submit "Add", :class => 'btn btn-default btn-lg'%>
                    <%end%>

                    </div>
                </div>
            </div>
        </div>

app/views/projects/show.html.erb
  

<div class="product-container"> 
  <div class="row" id="ProductInfo">
    <div class="col-lg-8 col-md-9">
      <div style="margin: 0px 40px">
        <div class="product-slider">
          <div id="carousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                  <div class="carousel-item active">   <%= image_tag @project.image1, :class => "d-block w-100" , :alt => "First slide"%> 
                  </div>
                    <div class="carousel-item">   <%= image_tag @project.images.first.name, :class => "d-block w-100" %> 
                    </div>

            </div>
          </div>
          <div class="clearfix">
            <div class="carousel-control">
                         <a class="carousel-control" href="#carousel" role="button" data-slide="prev">
                   <span class="carousel-control-prev-icon" aria-hidden="true"></span></i> </a> 
                  <a class="carousel-control" href="#carousel" role="button" data-slide="next"> 
                    <span class="carousel-control-next-icon" aria-hidden="true"></span> </a> </div>
            </div>

                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner">
                    <div class="item active">
                      <div data-target="#carousel" data-slide-to="0" class="thumb"> <%= image_tag @project.image1%> </div>
                      <div data-target="#carousel" data-slide-to="2" class="thumb"> <%= image_tag @project.images.first.name%></div>

                      
                     
                    </div>
                    <div class="carousel-item">
                      <div data-target="#carousel" data-slide-to="5" class="thumb"><img src="http://placehold.it/100x80?text=Thumb+06"></div>
                      <% if  @images.third.present? %>

                      <div data-target="#carousel" data-slide-to="4" class="thumb"> <%= image_tag @project.images.third.name%></div>
                      <%end %>
                      <div data-target="#carousel" data-slide-to="6" class="thumb"><img src="http://placehold.it/100x80?text=Thumb+07"></div>
                    </div>
                    
               </div>
                <!-- <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev"> <i class="fa fa-angle-left" aria-hidden="true"></i> </a> <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next"><i class="fa fa-angle-right" aria-hidden="true"></i> </a>  -->
              </div>
             </div>
          </div>
        </div>

          <div class="col-lg-4 col-md-3">
            <div class="project-intro">
              <h2 class="project-title"><%= @project.title %></h2>
              <p class="project-description"><%= @project.description %></p>
            </div>  
          </div>
      </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   <%= link_to root_path do %>
    <%= image_tag "logo.png", :class => "navbar-img navbar-brand"%>
    <% end %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="nav navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item ">
        <%= link_to"项目 Projects",projects_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to"新闻 News",home_news_path, class:"nav-link"%>  
      </li>
      <li class="nav-item">
         <%= link_to"关于 About",home_about_path, class:"nav-link"%> 
      </li>
       <li class="nav-item">
         <%= link_to"联系 Contact",home_contact_path, class:"nav-link"%> 
      </li>
    </ul>
  </div>
</nav>